=== fohl/swonder/wonder3.1.9/dtd/fwonder_config.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
     *                                                                                   *
     *  WONDER - Wave field synthesis Of New Dimensions of Electronic music in Realtime  *
     *  http://swonder.sourceforge.net                                                   *
     *                                                                                   *
     *                                                                                   *
     *  Technische UniversitÃ¤t Berlin, Germany                                           *
     *  Audio Communication Group                                                        *
     *  www.ak.tu-berlin.de                                                              *
     *  Copyright 2006-2008                                                              *
     *                                                                                   *
     *                                                                                   *
     *  This program is free software; you can redistribute it and/or modify             *
     *  it under the terms of the GNU General Public License as published by             *
     *  the Free Software Foundation; either version 2 of the License, or                *
     *  (at your option) any later version.                                              *
     *                                                                                   *
     *  This program is distributed in the hope that it will be useful,                  *
     *  but WITHOUT ANY WARRANTY; without even the implied warranty of                   *
     *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                    *
     *  GNU General Public License for more details.                                     *
     *                                                                                   *
     *  You should have received a copy of the GNU General Public License                *
     *  along with this program; if not, write to the Free Software                      *
     *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.       *
     *                                                                                   *
     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */ -->

<!ELEMENT fwonder_config (jack,brir,impulseresponse,tail?,static_ir_matrix?,dynamic_ir_matrix?,advanced_settings?) >



<!ELEMENT jack EMPTY>
<!ATTLIST jack
  name                  CDATA  #REQUIRED
  number_of_sources     CDATA  #REQUIRED
  number_of_outputs     CDATA  #REQUIRED
>



<!ELEMENT brir (azimuth, elevation)>
<!ATTLIST brir
  path    CDATA  #REQUIRED
>

<!ELEMENT azimuth EMPTY>
<!ATTLIST azimuth
  start       CDATA  #REQUIRED
  stop        CDATA  #REQUIRED
>

<!ELEMENT elevation EMPTY>
<!ATTLIST elevation
  start       CDATA  #REQUIRED
  stop        CDATA  #REQUIRED
>



<!ELEMENT impulseresponse EMPTY>
<!ATTLIST impulseresponse
  do_crossfades    (1|0)  #REQUIRED
  max_length       CDATA  #REQUIRED
>



<!ELEMENT tail EMPTY>
<!ATTLIST tail
  name             CDATA               #REQUIRED
  max_length       CDATA               #REQUIRED
  partition_size   CDATA               #REQUIRED
  window           (LINEAR|COS2|NOWIN) #REQUIRED
  do_crossfades    (1|0)               #REQUIRED
  offset           CDATA               #REQUIRED
>



<!ELEMENT static_ir_matrix EMPTY>
<!ATTLIST static_ir_matrix
  x_resolution  CDATA  #REQUIRED
  y_resolution  CDATA  #REQUIRED
>



<!ELEMENT dynamic_ir_matrix EMPTY>
<!ATTLIST dynamic_ir_matrix
  x_resolution          CDATA  #REQUIRED
  y_resolution          CDATA  #REQUIRED
  x_radius              CDATA  #REQUIRED
  y_radius              CDATA  #REQUIRED
>



<!ELEMENT advanced_settings EMPTY>
<!ATTLIST advanced_settings
  resolution_changeable (1|0) #REQUIRED
>

=== fohl/swonder/wonder3.1.9/configs/fwonder_config.xml
<?xml version="1.0"?>

<!--/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
     *                                                                                   *
     *  WONDER - Wave field synthesis Of New Dimensions of Electronic music in Realtime  *
     *  http://swonder.sourceforge.net                                                   *
     *                                                                                   *
     *                                                                                   *
     *  Technische UniversitÃ¤t Berlin, Germany                                           *
     *  Audio Communication Group                                                        *
     *  www.ak.tu-berlin.de                                                              *
     *  Copyright 2006-2008                                                              *
     *                                                                                   *
     *                                                                                   *
     *  This program is free software; you can redistribute it and/or modify             *
     *  it under the terms of the GNU General Public License as published by             *
     *  the Free Software Foundation; either version 2 of the License, or                *
     *  (at your option) any later version.                                              *
     *                                                                                   *
     *  This program is distributed in the hope that it will be useful,                  *
     *  but WITHOUT ANY WARRANTY; without even the implied warranty of                   *
     *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                    *
     *  GNU General Public License for more details.                                     *
     *                                                                                   *
     *  You should have received a copy of the GNU General Public License                *
     *  along with this program; if not, write to the Free Software                      *
     *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.       *
     *                                                                                   *
     * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */ -->

<!DOCTYPE fwonder_config SYSTEM "fwonder_config.dtd">

<fwonder_config>

    <jack name="fwonder" number_of_sources="1" number_of_outputs="2"/>

    <brir path="/home/fwonderuser/IR">
        <azimuth start="-1" stop="1"/> 
        <elevation start="-1" stop="1"/>
    </brir>

    <impulseresponse do_crossfades="0" max_length="16384"/>

    <tail name="tail" max_length="0" partition_size="8192" window="LINEAR" do_crossfades="0" offset="0"/>

    <static_ir_matrix x_resolution="8" y_resolution="8" />

    <dynamic_ir_matrix x_resolution="1" y_resolution="1" x_radius="4" y_radius="4" />

    <advanced_settings resolution_changeable="0"/>

</fwonder_config>
